### ISSUE TITLE
Login script error

### ISSUE THREAD

**Issue by joeypatino** [vecna/mobilizon-poster#4]
Hi Claudio,

When using the login script and using the --longopts, the command fails with the stack trace as shown below. All node_modules are installed and I'm using node v12.10.0.

`node bin/login.js --login EMAIL --password PASSWORD`

```
.json decode error? TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/Users/joey/mobilizon-poster/node_modules/node-fetch/lib/index.js:1305:9)
    at /Users/joey/mobilizon-poster/node_modules/node-fetch/lib/index.js:1410:19
    at new Promise (<anonymous>)
    at fetch (/Users/joey/mobilizon-poster/node_modules/node-fetch/lib/index.js:1407:9)
    at Object.mobilizoneHTTPAPIfetch (/Users/joey/mobilizon-poster/lib/shared.js:65:18)
    at Object.perform (/Users/joey/mobilizon-poster/lib/login.js:22:39)
    at connectAndSaveTokens (/Users/joey/mobilizon-poster/bin/login.js:25:31)
    at Object.<anonymous> (/Users/joey/mobilizon-poster/bin/login.js:40:1)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
```

I looked into the code and it appears that there might be a missing configuration value for `api`? Should this be an included config option (`--api`), and if so what's the correct URL?

**Comment by vecna** [comment]
Thanks @joeypatino and sorry if I didn't saw the issue before.
The problem is with the fact that exist a config file, not part of the repository:

```
$ cat .gitignore
node_modules/*
eventlog/*

config.json
identities.json
groups.json
```
```

$ cat config.json
{
  "api":"https://mobilize.berlin/api"
}
```

and that contribute in composing the URL, which do not looks absolute for the fetch call.

it is a lack of a sanity check, thanks for spotting it

**Comment by vecna** [comment]
```
$ bin/location.js --address "Basilea, Svizzera"
address Basilea, Svizzera
Identities found 1 (Unofficial—Reposting) token acquired!
Fetched 1 possible locations, the first is:
{
  __typename: 'Address',
  country: 'Switzerland',
  description: 'Basel',
  geom: '7.5878261;47.5581077',
  id: null,
  locality: null,
  originId: 'nominatim:1683619',
  postalCode: null,
  region: 'Basel-City',
  street: ' ',
  type: 'administrative',
  url: null
}


$ mv config.json xxx


$ bin/location.js --address "Basilea, Svizzera"
address Basilea, Svizzera
Identities found 1 (Unofficial—Reposting) token acquired!
Error: you should specify an API url with option --api, or in config.json
The URL should be absolute, for example, in config.json: { "api":"https://mobilize.berlin/api" }
```
